-- ChainTruth | 00_setup.sql
-- Database, schemas, warehouse, persona roles. Run as ACCOUNTADMIN (or a role that can create roles).
USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS SC_ONTOLOGY;
CREATE SCHEMA   IF NOT EXISTS SC_ONTOLOGY.RAW;         -- source systems as-is (messy)
CREATE SCHEMA   IF NOT EXISTS SC_ONTOLOGY.CURATED;     -- canonical, conformed layer
CREATE SCHEMA   IF NOT EXISTS SC_ONTOLOGY.ONTOLOGY;    -- ontology metadata + semantic view + search
CREATE SCHEMA   IF NOT EXISTS SC_ONTOLOGY.GOVERNANCE;  -- policies, tags, tests, alerts
CREATE SCHEMA   IF NOT EXISTS SC_ONTOLOGY.APP;         -- agent + streamlit

CREATE WAREHOUSE IF NOT EXISTS SC_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

-- Persona roles (the "same metric, three personas" demo)
CREATE ROLE IF NOT EXISTS PLANNER_ROLE;
CREATE ROLE IF NOT EXISTS PROCUREMENT_ROLE;
CREATE ROLE IF NOT EXISTS LOGISTICS_ROLE;

SET me = CURRENT_USER();
GRANT ROLE PLANNER_ROLE     TO USER IDENTIFIER($me);
GRANT ROLE PROCUREMENT_ROLE TO USER IDENTIFIER($me);
GRANT ROLE LOGISTICS_ROLE   TO USER IDENTIFIER($me);

GRANT USAGE ON WAREHOUSE SC_WH TO ROLE PLANNER_ROLE;
GRANT USAGE ON WAREHOUSE SC_WH TO ROLE PROCUREMENT_ROLE;
GRANT USAGE ON WAREHOUSE SC_WH TO ROLE LOGISTICS_ROLE;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE PLANNER_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE PROCUREMENT_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE LOGISTICS_ROLE;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_AGENT_USER TO ROLE PLANNER_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_AGENT_USER TO ROLE PROCUREMENT_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_AGENT_USER TO ROLE LOGISTICS_ROLE;

USE DATABASE SC_ONTOLOGY;
USE WAREHOUSE SC_WH;
