-- ChainTruth | 07_grants.sql  (run after everything else exists)
USE ROLE ACCOUNTADMIN; USE DATABASE SC_ONTOLOGY;

GRANT USAGE ON DATABASE SC_ONTOLOGY TO ROLE PLANNER_ROLE;
GRANT USAGE ON DATABASE SC_ONTOLOGY TO ROLE PROCUREMENT_ROLE;
GRANT USAGE ON DATABASE SC_ONTOLOGY TO ROLE LOGISTICS_ROLE;

-- Same grants for the three personas
EXECUTE IMMEDIATE $$
DECLARE
  roles ARRAY DEFAULT ['PLANNER_ROLE','PROCUREMENT_ROLE','LOGISTICS_ROLE'];
  r STRING;
BEGIN
  FOR i IN 0 TO ARRAY_SIZE(:roles) - 1 DO
    r := GET(:roles, :i)::STRING;
    EXECUTE IMMEDIATE 'GRANT USAGE ON SCHEMA SC_ONTOLOGY.CURATED TO ROLE ' || :r;
    EXECUTE IMMEDIATE 'GRANT USAGE ON SCHEMA SC_ONTOLOGY.ONTOLOGY TO ROLE ' || :r;
    EXECUTE IMMEDIATE 'GRANT USAGE ON SCHEMA SC_ONTOLOGY.GOVERNANCE TO ROLE ' || :r;
    EXECUTE IMMEDIATE 'GRANT USAGE ON SCHEMA SC_ONTOLOGY.APP TO ROLE ' || :r;
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN SCHEMA SC_ONTOLOGY.CURATED TO ROLE ' || :r;
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN SCHEMA SC_ONTOLOGY.ONTOLOGY TO ROLE ' || :r;
    EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN SCHEMA SC_ONTOLOGY.GOVERNANCE TO ROLE ' || :r;
    EXECUTE IMMEDIATE 'GRANT SELECT ON SEMANTIC VIEW SC_ONTOLOGY.ONTOLOGY.SV_SUPPLY_CHAIN TO ROLE ' || :r;
    EXECUTE IMMEDIATE 'GRANT USAGE ON CORTEX SEARCH SERVICE SC_ONTOLOGY.ONTOLOGY.CONTRACT_SEARCH TO ROLE ' || :r;
    EXECUTE IMMEDIATE 'GRANT USAGE ON AGENT SC_ONTOLOGY.APP.SUPPLY_CHAIN_AGENT TO ROLE ' || :r;
  END FOR;
  RETURN 'grants applied';
END;
$$;
