-- ChainTruth | 08_role_snapshot.sql
-- Captures what each persona role can see (with USE SECONDARY ROLES NONE).
-- The Streamlit app reads this table to show governance side-by-side.
USE ROLE ACCOUNTADMIN; USE DATABASE SC_ONTOLOGY; USE WAREHOUSE SC_WH;

CREATE OR REPLACE TABLE SC_ONTOLOGY.GOVERNANCE.ROLE_VISIBILITY_SNAPSHOT (
  captured_at TIMESTAMP_NTZ,
  role_name STRING,
  metric_name STRING,
  metric_value FLOAT,
  is_masked BOOLEAN
);

GRANT INSERT ON TABLE SC_ONTOLOGY.GOVERNANCE.ROLE_VISIBILITY_SNAPSHOT TO ROLE PLANNER_ROLE;
GRANT INSERT ON TABLE SC_ONTOLOGY.GOVERNANCE.ROLE_VISIBILITY_SNAPSHOT TO ROLE PROCUREMENT_ROLE;
GRANT INSERT ON TABLE SC_ONTOLOGY.GOVERNANCE.ROLE_VISIBILITY_SNAPSHOT TO ROLE LOGISTICS_ROLE;
GRANT SELECT ON TABLE SC_ONTOLOGY.GOVERNANCE.ROLE_VISIBILITY_SNAPSHOT TO ROLE PLANNER_ROLE;
GRANT SELECT ON TABLE SC_ONTOLOGY.GOVERNANCE.ROLE_VISIBILITY_SNAPSHOT TO ROLE PROCUREMENT_ROLE;
GRANT SELECT ON TABLE SC_ONTOLOGY.GOVERNANCE.ROLE_VISIBILITY_SNAPSHOT TO ROLE LOGISTICS_ROLE;

-- Clear previous snapshot data before re-capturing
TRUNCATE TABLE SC_ONTOLOGY.GOVERNANCE.ROLE_VISIBILITY_SNAPSHOT;

-- Populate under each role with secondary roles disabled to capture masking
USE ROLE PLANNER_ROLE; USE SECONDARY ROLES NONE; USE WAREHOUSE SC_WH;
INSERT INTO SC_ONTOLOGY.GOVERNANCE.ROLE_VISIBILITY_SNAPSHOT
SELECT CURRENT_TIMESTAMP(), 'PLANNER_ROLE', m.metric, m.val, m.val IS NULL
FROM (
  SELECT 'otd_pct' AS metric, otd_pct AS val FROM SEMANTIC_VIEW(SC_ONTOLOGY.ONTOLOGY.SV_SUPPLY_CHAIN METRICS order_lines.otd_pct)
  UNION ALL SELECT 'fill_rate_pct', fill_rate_pct FROM SEMANTIC_VIEW(SC_ONTOLOGY.ONTOLOGY.SV_SUPPLY_CHAIN METRICS order_lines.fill_rate_pct)
  UNION ALL SELECT 'in_full_pct', in_full_pct FROM SEMANTIC_VIEW(SC_ONTOLOGY.ONTOLOGY.SV_SUPPLY_CHAIN METRICS order_lines.in_full_pct)
  UNION ALL SELECT 'avg_days_late', avg_days_late FROM SEMANTIC_VIEW(SC_ONTOLOGY.ONTOLOGY.SV_SUPPLY_CHAIN METRICS order_lines.avg_days_late)
  UNION ALL SELECT 'days_of_inventory', days_of_inventory FROM SEMANTIC_VIEW(SC_ONTOLOGY.ONTOLOGY.SV_SUPPLY_CHAIN METRICS inventory.days_of_inventory)
  UNION ALL SELECT 'avg_landed_cost_per_unit', avg_landed_cost_per_unit FROM SEMANTIC_VIEW(SC_ONTOLOGY.ONTOLOGY.SV_SUPPLY_CHAIN METRICS order_lines.avg_landed_cost_per_unit)
) m;

USE ROLE PROCUREMENT_ROLE; USE SECONDARY ROLES NONE; USE WAREHOUSE SC_WH;
INSERT INTO SC_ONTOLOGY.GOVERNANCE.ROLE_VISIBILITY_SNAPSHOT
SELECT CURRENT_TIMESTAMP(), 'PROCUREMENT_ROLE', m.metric, m.val, m.val IS NULL
FROM (
  SELECT 'otd_pct' AS metric, otd_pct AS val FROM SEMANTIC_VIEW(SC_ONTOLOGY.ONTOLOGY.SV_SUPPLY_CHAIN METRICS order_lines.otd_pct)
  UNION ALL SELECT 'fill_rate_pct', fill_rate_pct FROM SEMANTIC_VIEW(SC_ONTOLOGY.ONTOLOGY.SV_SUPPLY_CHAIN METRICS order_lines.fill_rate_pct)
  UNION ALL SELECT 'in_full_pct', in_full_pct FROM SEMANTIC_VIEW(SC_ONTOLOGY.ONTOLOGY.SV_SUPPLY_CHAIN METRICS order_lines.in_full_pct)
  UNION ALL SELECT 'avg_days_late', avg_days_late FROM SEMANTIC_VIEW(SC_ONTOLOGY.ONTOLOGY.SV_SUPPLY_CHAIN METRICS order_lines.avg_days_late)
  UNION ALL SELECT 'days_of_inventory', days_of_inventory FROM SEMANTIC_VIEW(SC_ONTOLOGY.ONTOLOGY.SV_SUPPLY_CHAIN METRICS inventory.days_of_inventory)
  UNION ALL SELECT 'avg_landed_cost_per_unit', avg_landed_cost_per_unit FROM SEMANTIC_VIEW(SC_ONTOLOGY.ONTOLOGY.SV_SUPPLY_CHAIN METRICS order_lines.avg_landed_cost_per_unit)
) m;

USE ROLE LOGISTICS_ROLE; USE SECONDARY ROLES NONE; USE WAREHOUSE SC_WH;
INSERT INTO SC_ONTOLOGY.GOVERNANCE.ROLE_VISIBILITY_SNAPSHOT
SELECT CURRENT_TIMESTAMP(), 'LOGISTICS_ROLE', m.metric, m.val, m.val IS NULL
FROM (
  SELECT 'otd_pct' AS metric, otd_pct AS val FROM SEMANTIC_VIEW(SC_ONTOLOGY.ONTOLOGY.SV_SUPPLY_CHAIN METRICS order_lines.otd_pct)
  UNION ALL SELECT 'fill_rate_pct', fill_rate_pct FROM SEMANTIC_VIEW(SC_ONTOLOGY.ONTOLOGY.SV_SUPPLY_CHAIN METRICS order_lines.fill_rate_pct)
  UNION ALL SELECT 'in_full_pct', in_full_pct FROM SEMANTIC_VIEW(SC_ONTOLOGY.ONTOLOGY.SV_SUPPLY_CHAIN METRICS order_lines.in_full_pct)
  UNION ALL SELECT 'avg_days_late', avg_days_late FROM SEMANTIC_VIEW(SC_ONTOLOGY.ONTOLOGY.SV_SUPPLY_CHAIN METRICS order_lines.avg_days_late)
  UNION ALL SELECT 'days_of_inventory', days_of_inventory FROM SEMANTIC_VIEW(SC_ONTOLOGY.ONTOLOGY.SV_SUPPLY_CHAIN METRICS inventory.days_of_inventory)
  UNION ALL SELECT 'avg_landed_cost_per_unit', avg_landed_cost_per_unit FROM SEMANTIC_VIEW(SC_ONTOLOGY.ONTOLOGY.SV_SUPPLY_CHAIN METRICS order_lines.avg_landed_cost_per_unit)
) m;

USE ROLE ACCOUNTADMIN; USE SECONDARY ROLES ALL;
SELECT role_name, metric_name, ROUND(metric_value, 2) AS val, is_masked
FROM SC_ONTOLOGY.GOVERNANCE.ROLE_VISIBILITY_SNAPSHOT ORDER BY metric_name, role_name;
