-- ChainTruth | 10_answer_cache.sql  (shared answer cache)
USE ROLE ACCOUNTADMIN; USE DATABASE SC_ONTOLOGY;

CREATE TABLE IF NOT EXISTS SC_ONTOLOGY.GOVERNANCE.ANSWER_CACHE (
    QUESTION_KEY       VARCHAR,
    QUESTION_TEXT      VARCHAR,
    ANSWER_TEXT        VARCHAR,
    SQL_TEXT           VARCHAR,
    EVIDENCE_JSON      VARCHAR,
    TOOLS              VARCHAR,
    ELAPSED_SECONDS    FLOAT,
    SAVED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DATA_VERSION       VARCHAR
);

-- Persona roles get SELECT only; the app writes as its owner (ACCOUNTADMIN).
EXECUTE IMMEDIATE $$
DECLARE
  roles ARRAY DEFAULT ['PLANNER_ROLE','PROCUREMENT_ROLE','LOGISTICS_ROLE'];
  r STRING;
BEGIN
  FOR i IN 0 TO ARRAY_SIZE(:roles) - 1 DO
    r := GET(:roles, :i)::STRING;
    EXECUTE IMMEDIATE 'REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON TABLE SC_ONTOLOGY.GOVERNANCE.ANSWER_CACHE FROM ROLE ' || :r;
    EXECUTE IMMEDIATE 'GRANT SELECT ON TABLE SC_ONTOLOGY.GOVERNANCE.ANSWER_CACHE TO ROLE ' || :r;
  END FOR;
  RETURN 'answer_cache grants applied (SELECT only)';
END;
$$;
